### ISSUE TITLE
RTCMultiConnection support on mobile browser???

### ISSUE THREAD

**Issue by NguyenTungs** [muaz-khan/RTCMultiConnection#165]
HiHi @muaz-khan !
I have a question to ask you !
RTCMultiConnection support on the phone ? If can , I want broadcast from desktop to the mobile browser?? How to fix it!
Thanks!

**Comment by muaz-khan** [comment]
RTCMultiConnection-v3 supports phonegap/cordova based iOS+Android applications:

* https://github.com/muaz-khan/RTCMultiConnection/blob/master/docs/ios-android.md

You can EVEN broadcast video from iOS/Android as well.

THE ONLY LIMITATION is, your mobile app can NOT share its screen. Otherwise everything else works fine from mobile-to-PC and vice versa.

**Comment by NguyenTungs** [comment]
Hi @muaz-khan !
Thank you for your answer. 
It means that from the web on your desktop can not broadcast on the mobile browser . Mobile only runs when developing app for it.
