### ISSUE TITLE
Switching RTCMultiConnection between channels

### ISSUE THREAD

**Issue by regularcoffee** [muaz-khan/RTCMultiConnection#24]
Hi Muaz,

Is there a way for a single RTCMultiConnection instance to dynamically switch between channels i.e. big-rooms?

What I want to do is to instantiate RTCMultiConnection with one channel, later switch it to use another channel, and then maybe come back to the original channel.

Thanks.

**Comment by muaz-khan** [comment]
The term "big channel" refers to socket that is NOT-only used for signaling, but also for presence detection and syncing statuses. That's why it is not possible in current implementations, to switch between sockets (big-rooms) without leaving session.

There is a `disconnect` method, that allows you close current channel and join another one. This method will close all existing peers, though. You can use `keepStreamsOpened` to keep all local streams "active".

```javascript
btnLeaveChannel.onclick = function() {
    connection.disconnect();

    connection.channel = 'new-channel';
    connection.connect();
};
```

**Comment by regularcoffee** [comment]
Thanks for the quick response.

The snippet has helped.

P.S.
Looking forward to the planned breaking/new updates #12.
