### ISSUE TITLE
WebSocket connection to 'wss://myhost.com' failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by AndyNormore** [muaz-khan/RTCMultiConnection#290]
USING THIS CONFIG WORKS FINE
<script src="https://rtcmulticonnection.herokuapp.com/dist/RTCMultiConnection.min.js"></script>
<script src="https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js"></script>
connection.socketURL = 'https://rtcmulticonnection.herokuapp.com:443'; 

USING THIS RESULTS IN THE ERROR: WebSocket connection to 'wss://myhost.com' failed: Error during WebSocket handshake: Unexpected response code: 400

connection.socketURL = 'https://socket.skyrooms.io';

**Comment by muaz-khan** [comment]
Its running here:

* http://socket.skyrooms.io:9001/socket.io/socket.io.js

i.e.

1. Listening port `9001`
2. On HTTP rather than HTTPs

To fix it:

1. [Force HTTPs](https://github.com/muaz-khan/RTCMultiConnection/blob/master/server.js#L6)
2. [Set port 9001 or 443](https://github.com/muaz-khan/RTCMultiConnection/blob/master/server.js#L9)

```javascript
var isUseHTTPs  = true;
var port = 443; // or 9001
```

Now this MUST/should work:

```javascript
// port+slash at the end: https://domain.com:9001/
connection.socketURL = 'https://socket.skyrooms.io:443/'; // or 9001
```

**Comment by AndyNormore** [comment]
Thank you Muaz, you're an excellence in this realm.
