### ISSUE TITLE
Question signaling server: About rooms and listOfUser[].connectedWith

### ISSUE THREAD

**Issue by OrlandoCo** [muaz-khan/RTCMultiConnection#341]
I have a question about why  the signaling server use a listOfUser[].connectedWith, to interact with users in the same room and not using the in build rooms functions of socket.io?

**Comment by muaz-khan** [comment]
Moderator is given more privileges and he can easily restrict and manage how his participants interconnects.

If you join a room, you are actually joining the `moderator`; and now he decides whether he should share other participants' mdatadata with you.

This mechanism makes sure that room always gets closed if moderator leaves. (simply removing user from `listOfUsers` array) Other users can reopen anytime.

I planned to make sure that 1-to-1 always gets happened, without of worrying about open-join-close rooms concept. Presence detection was also made easier because now users connects each other using their `user-ids` rather than `room-ids`.

Single user can join multiple rooms as well. Because he's actually joining moderators using their `user-ids`.

**Comment by erickzkie027** [comment]
I always get an empty object when trying to console listOfUser[].connectedWith. I want to broadcast only on the room, but it shows me empty object (seems like no user connected). How will I broadcast it only on specific room ?
