### ISSUE TITLE
RTCMulticonnection V3 screensharing not working in firefox

### ISSUE THREAD

**Issue by manurajmr1** [muaz-khan/RTCMultiConnection#342]
this one not working in firefox - https://rtcmulticonnection.herokuapp.com/demos/Scalable-Screen-Broadcast.html

Can you please look on it

**Comment by muaz-khan** [comment]
Please download this:

* https://github.com/muaz-khan/Firefox-Extensions/tree/master/enable-screen-capturing

Modify `index.js` to include `rtcmulticonnection.herokuapp.com` here:

* https://github.com/muaz-khan/Firefox-Extensions/blob/master/enable-screen-capturing/index.js#L11

Make ZIP and rename `.zip` to `.xpi` and install by dragging/dropping over Firefox address-bar.

Otherwise follow these steps:

* https://github.com/muaz-khan/Firefox-Extensions/tree/master/enable-screen-capturing#how-to-deploy

## Otherwise

Open `about:config` and search for `media.getusermedia.screensharing.allowed_domains`.

Now manually append at the end of the list: `rtcmulticonnection.herokuapp.com`

**Comment by manurajmr1** [comment]
Open about:config and search for media.getusermedia.screensharing.allowed_domains.
Now manually append at the end of the list: rtcmulticonnection.herokuapp.com

This one made it working. Thanks !

So one doubt,  RTC multiconnection  V2 worked fine in firefox,  but  in V3  i have to do it like this to make it working, why is it so?

Why RTC multiconnection V3 is using a node server is it possible to do it without setting up node server just like V2 using firebase.js. which version il be better to use

**Comment by muaz-khan** [comment]
All demos from v2 was deployed here:

* https://www.webrtc-experiment.com/RTCMultiConnection/

However v3 demos are using a separate server:

* https://rtcmulticonnection.herokuapp.com/

v3 is using socket.io to get maximum accuracy in the handshake and presence detection.

v3 supports Firebase+PubNub+WebSocket+many others as well. You can check demos in the "demos" directory.

**Comment by manurajmr1** [comment]
Thanks you muaz for the quick reply.
