### ISSUE TITLE
Question about iceServers.push(getTURNObj)

### ISSUE THREAD

**Issue by Patrick-Vogt** [muaz-khan/RTCMultiConnection#357]
Hi Muaz, 

I have a problem to understand the way how following works:

In "  var iceServers = [];" I have two self hosted TURN-Servers (CoTurn). 
Why are **both** servers involved if a connection is established? I thought it will grab the first TURN-Server and jump to the second if the first is not available.

Will the data be relayed over both turnservers? So it would be recommended to set only one TURN-Server in the array and manually change it, if one of them crashes? 

Thank you in advance!

**Comment by muaz-khan** [comment]
> "....why are both servers involved if a connection is established?...."

Following things should happen:

1. Browser must capture all (possible) pairs based on ICE array (URIs)
2. It should take only prioritized or better-looking addresses; and make STUN-binding requests to validate those addresses
3. Browser must use first valid (+active) address to perform DTLS handshake; if no active pair found then it should check for other addresses; otherwise, simply disconnect

A browser should NOT care if any of the ICE_uri fails to load or respond.

> "....i thought it will grab the first TURN-Server and jump to the second if the first is not available......"

A user can listen for `oniceconnectionstatechange` event to check if ice disconnected or failed. He can provide other TURN addresses and renegotiate or recreate peer(s).

`ice-failed` doesn't mean that TURN is down; it can be

1. Either TURN is down and no other methods (ICE) to fetch fresh pairs
2. NAT+Firewall played their role to reject all active+prioritized addresses

It will be a long process to

1. wait for `oniceconnectionstatechange`
2. recreate or renegotiate with separate TURN address(es)

**Browser should auto decide which TURN-pair to use for handshake. It should fallback (retry) until all active addresses fail.**

> "....will the data be relayed over both turnservers?...."

It depends. Usually chrome uses single address for all tracks; in this case, only one TURN port will be used to relay RTP+RTCP data packets.

If we ask chrome to use separate ip for each track then it is possible that audio track uses one TURN and video uses other. However, remember, this is not the default behavior. So it doesn't happens in existing demos.

**Comment by Patrick-Vogt** [comment]
Thank you for your answer, this helps a lot! .-)
