### ISSUE TITLE
Number of users in a room?

### ISSUE THREAD

**Issue by wizzed** [muaz-khan/RTCMultiConnection#385]
Is there a way to get the number of users in a room?

**Comment by async3619** [comment]
I think you should modify client/server code of RTCMultiConnection to identify several informations. I had edited the code to determine get all of participants **before webrtc connection**. and it works fine.

**Comment by muaz-khan** [comment]
You can get list of connected user-ids using [`getAllParticipants`](http://www.rtcmulticonnection.org/docs/getAllParticipants/) method.

```javascript
connection.getAllParticipants().forEach(function(participantId) {
    var user = connection.peers[participantId];
    var hisFullName = user.extra.fullName;
    var hisUID = user.userid;
    var hisNativePeer = user.peer;
    var hisIncomingStreams = user.peer.getRemoteStreams();
    var hisDataChannels = user.channels;
});
```

You can sync/share/exchange above information with single or multiple users using either

1. WebRTC data channels `connection.session.data=true`
2. Or socket.io messaging [`demo`](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/custom-socket-event.html)

```javascript
connection.socket.emit(connection.socketCustomEvent, {
    participants: connection.getAllParticipants()
});
```

See how [`this demo`](https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/custom-socket-event.html) listens for above custom events.

You can use same custom messaging (through socket.io) to share pre-information or early data before joining a room.

For example, you can check who is in the room before joining it.

You can share extra information as well e.g. participants photos, locations etc.

Next v3-version is going to naively support such features. Because rooms are now separated in the `listOfRooms` array on server side.

Initial (minor) implementation is available here:

* https://github.com/muaz-khan/RTCMultiConnection/tree/v3_rooms_implementation

However I can not recommend to upgrade to this version in the moment. Keep using `master` branch.
