### ISSUE TITLE
Video Conferencing - 100% CPU usage for 4 users.

### ISSUE THREAD

**Issue by mohamadhussain** [muaz-khan/RTCMultiConnection#485]
When I start a conference and connect 4 or more users `(all users in same browser and different tab)` in [Video Conferencing](https://rtcmulticonnection.herokuapp.com/demos/Video-Conferencing.html) demo the CPU usage reaches to 100%. 

> **My PC configuration**
>Windows 10
>Core i5-7400, 3.00 GHz
>RAM : 16 GB
>Browser : Chrome, Version 60.0.3112.113

Is it a normal behavior in RTCMulticonnection?

**Comment by avspeed** [comment]
it is normal .. mesh scenario .. you are encoding many videos in parallel on your machine and that requires a lot of cpu power

**Comment by muaz-khan** [comment]
Single peer requires about 100 to 150 mega bits of the RAM.

RTCMultiConnection do not support media servers. You can try jitsi (SFU) to fix such issues (maybe).

Otherwise [force 360p](http://www.rtcmulticonnection.org/docs/mediaConstraints/) for each peer, and [force vp9](http://www.rtcmulticonnection.org/docs/processSdp/) as well. Disable echoCancellation as well as voiceActivityDetection. Set `connection.optionalArgument=null`.

You can [force bandwidth](http://www.rtcmulticonnection.org/docs/bandwidth/) as well e.g. 30 kbits/s for audio and 50 kbits/s for video.

**Comment by zhangalex** [comment]
Is there any way make RTCMultiConnection connect to jitsi (SFU) server?

**Comment by WJdenghuo** [comment]
Is there any way make RTCMultiConnection  to be (SFU) server
