### ISSUE TITLE
Chat mode - Name and Date

### ISSUE THREAD

**Issue by FlorianHergo** [muaz-khan/RTCMultiConnection#542]
Hello,

Can you explain to me how to recover the name and the date of the different people, for each text inserted, in a communication chat.

Perhaps, add parameter in :
function appendDIV(event) 

Thx for your help.

**Comment by Ladoli** [comment]
You can overwrite appendDiv with your own version that can take in the extra parameters. So in your html script section you can put 

function appendDIV(event, name){
       let date = new Date(); <--- Convert to whatever format you want it..
       chatcontainer.append(name + ": " + event + " " + date);
       /* The rest of the code will mirror the current appendDIV function with modifications based on showing name and date*/
}

A lazy way of doing it too would be 

var message = name + ": " + event + " " + date;
and then just call appendDIV(message) instead of appendDIV(event).
