### ISSUE TITLE
socket.io.js (Service Unavailable)

### ISSUE THREAD

**Issue by markokoh** [muaz-khan/RTCMultiConnection#663]
Hi. I'm getting this error with socket.io.js. All was fine yesterday - started happenning today (11/1/18):

GET https://rtcmulticonnection.herokuapp.com/socket.io/socket.io.js 503 (Service Unavailable)

Any ideas?

Thanks,

Mark

**Comment by dantutu** [comment]
Hi @markokoh i started some research about it, but I didn't find yet any solve for this.  I have my own server installed and when I tried to use I had the same problem.

**Comment by muaz-khan** [comment]
Heroku has issues. That's why I'm planning to move codes to `RTCMultiConnection.org`. And signaling server will run here:

```
https://webrtcweb.com:9002/
```

Both `socket.io.js` and all other files will be served through `rtcmulticonnecion.org`. I'll block this:

```
https://webrtcweb.com:9002/socket.io/socket.io.js
```

@dantutu Did you use heroku for your own server or a custom non-heroku hosting?

**Comment by WebSavvyGuy** [comment]
Looks like its fixed now.

**Comment by muaz-khan** [comment]
Yes. It was HEOKU issue. They were repairing SSL on all of their services. So it affected all apps hosted on heroku. Or at least those that published new content.
