### ISSUE TITLE
Empty package

### ISSUE THREAD

**Issue by Fi1osof** [muaz-khan/RTCMultiConnection#666]
Package installed from https://www.npmjs.com/package/rtcmulticonnection-v3 contains only README.md and package.json files.

**Comment by muaz-khan** [comment]
If you open [that link](https://www.npmjs.com/package/rtcmulticonnection-v3), it says it is moved here:
* https://www.npmjs.com/package/rtcmulticonnection

```sh
npm install rtcmulticonnection
```

**Reason:** previously I was supporting v2.2.2 as well. Which is now deprecated and doesn't works on Firefox/Edge or Safari11. That's why v3 codes are moved to main NPM package.

**Comment by Fi1osof** [comment]
So sorry! I am blind...(((
