### ISSUE TITLE
Add audio to broadcasting

### ISSUE THREAD

**Issue by Proxy08** [muaz-khan/RTCMultiConnection#728]
Hi Muaz,
Thank you for your works.

I want to know if it is possible to add audio stream to participant(viewer) in scalable broadcasting?
Let's say A broadcasts video and audio to B C D E F .... and A wants to talk directly D while broadcasting, I was thinking to AddStream to specific peer id?

**Comment by muaz-khan** [comment]
I'll recommend this:
1. Use socket.io custom messaging to send chat messages or share data among all users
2. Send a message like this: `"please-share-your-audio-with-me"`
3. The selected person should create a new/separate RTCMultiConnection object to start a ONE_TO_ONE room
4. Now he need to send room-id to the broadcaster so that broadcaster can join that room using a new/parallel RTCMultiConnection object.

Snippets:

```javascript
connection.socket.emit(connection.socketCustomEvent, {
    shareYourAudio: true,
    messageFor: 'remote-user-id'
});

connection.socket.on(connection.socketCustomEvent, function(message) {
    if (message.messageFor === connection.userid) {
        if (message.shareYourAudio === tru) {
            // create new RTCMultiConnection
            setupNewRTCMultiConnectionForAudio(function(connection2) {
                // share roomid back with the broadcaster
                connection.socket.emit(connection.socketCustomEvent, {
                    pleaseJoinThisAudioRoom: true,
                    roomid: connection2.sessionid
                });
            });
        }

        if (message.pleaseJoinThisAudioRoom === true) {
            // broadcaster will join audio room here
            joinNewRTCMultiConnectionForAudio(message.roomid);
        }
    }
});
```

**Comment by Proxy08** [comment]
Thanks Sir!
