### ISSUE TITLE
Why RTCMultiConnection is not gonna be updated?

### ISSUE THREAD

**Issue by VShtaba** [muaz-khan/RTCMultiConnection#757]
Muaz hello.  I read today that the project will no longer be updated:
'Please Try 3rd Party Codes Instead...
Try RTCMultiConnection at your own risk!
It is not gonna be updated from now on.
 4/17/2019' https://github.com/muaz-khan/RTCMultiConnection/blob/master/README.md

You have done a great job.  Volunteers use your library in our project. Thanks you!

What happened?  Are there vulnerabilities and security issues in the code? Are you closing your project?

**Comment by muaz-khan** [comment]
Default demos do not work without a TURN-server. That's the issue. Maybe I should provide only github codes and remove `herokuapp` demos.

The actual code works. But relies on TURN-servers. You know that.

I'll update readme and remove all demos soon.

**Comment by VShtaba** [comment]
Thanks for your reply. 
Did I understand your problem correctly, that the demo traffic goes through the TURN-server and the service support is expensive?
If so, I understand the problem.

**Comment by matiaslopezd** [comment]
@muaz-khan thanks for this awesome project! 👏 👏 

I have a question about TURN-servers and costs. I want use your project for my startup, but I want know more about costs because we used a lot of open source videoconference projects but this is very interesting for the P2P connection between many participants in the video, meaning less costs.

In the description of repository says:

> WebRTC JavaScript library for peer-to-peer applications (screen sharing, audio/video conferencing, file sharing, media streaming etc.)

I understand that the main functionality is provide a multi P2P connection with a signaling server for discover connection between users. But **is strictly necesary use a TURN server** (`connection.iceServers`)? I mean, this project have the difference between others because not necessarily use TURN servers for videoconferences and can work only with signaling server? I know that the firewalls and networks problems can cause use TURN servers, but I'm very interested in multi P2P connection!

**And finally only if you can and want :satisfied: say me the average cost you pay for the TURN servers used in the demos?** :pray:
 
We don't started using it yet but I want to take it in consideration for the new develop! :clap:

**Tell me that is possible only with signaling server, because I talk every day about your project!** 😄

Can I email you? :love_letter:

Thanks you and keep it up! :muscle:

**Comment by matiaslopezd** [comment]
I want contribute to this project with a new wiki and also create a manage _open collective_ profile! What do you think @muaz-khan ? 😄

**Comment by Patrick-Vogt** [comment]
In my experience, less than 50% of the transmissions needs a TURN-Server, but nevertheless it's good to have.

In case someone is in need: It runs well on 5$ machines from digital ocean and other providers. At least for development usage.

**Comment by IndranilSarkar87** [comment]
> Default demos do not work without a TURN-server. That's the issue. Maybe I should provide only github codes and remove `herokuapp` demos.
> 
> The actual code works. But relies on TURN-servers. You know that.
> 
> I'll update readme and remove all demos soon.

Hi Muaz,

You have done great job all the journey Webrtc and it is being sad that there will be no more updates from you now. Your contributions and efforts are remarkable, and I also wonder why not there is donate button using paypal, we all are happy to contribute as yours demos are really unbeatable
