### ISSUE TITLE
Error if initiator leaves

### ISSUE THREAD

**Issue by kekkopop** [muaz-khan/RTCMultiConnection#82]
in a video conference if the initiator leaves (e.g if initiator reloads the page ) then all other users get following error. 
```
Uncaught TypeError: Cannot read property 'iceConnectionState' of nullPeerInitiator.peer.oniceconnectionstatechange.peer.onsignalingstatechange @ RTCMultiConnection.js:2537
```
sometimes there is another error for maximum call stack exceeded - at peer.nativeClose() line

**Comment by Mithrillion** [comment]
I am still not sure if this will cause further issues, but the problem seems to be in this function:
peer.oniceconnectionstatechange = peer.onsignalingstatechange = function() {...}
Simply wrapping a if(peer){...} around the function body seems to prevent the error without any observed consequences so far, but I have not tested this thoroughly. I think the possible reason for the error is that the current code does not take into account that the "peer" object can be removed by some external code when the remote peer is disconnected.
